Fix for 409 error on pushing claims with duplicate IDs
adsabs/orcid-service pull request #41
Opened 2021-03-10 14:58 UTC by kelockhart

2021-03-10 16:09 UTC, marblestation requested changes
It looks good, but I think it would be nice to have a way out of the loop to make sure we never get trapped there. Let me know what you think!

2021-03-10 16:09 UTC, marblestation commented on orcid_service/views.py
> +                                       json=payload, headers=headers)
I think it would be a good idea to have another way out of this loop, I fear it can happen (even if it may not seem logical right now) that we get a 409 and removing arXiv/doi does not fix the 409 so we get trapped here. We can have a counter and get out if it goes beyond N.

2021-03-10 19:51 UTC, kelockhart commented on orcid_service/views.py
> +                                       json=payload, headers=headers)
Ah right. I meant to do that and just... didn't.

2021-03-11 07:34 UTC, marblestation approved these changes
Great! Ready to go!

2021-03-11 15:47 UTC, merged